### ISSUE TITLE
求 Mac 版 

### ISSUE THREAD

**Issue by zygds** [BeichenDream/Godzilla#23]
Mac m1 air 报错 
```log
└─$ java -jar Godzilla-V2.96.jar 
[!] Time:2021-02-22 12:33:45 ThreadId:1 Message: 不支持的Java Ui 版本 
[!] Time:2021-02-22 12:33:45 ThreadId:1 Message:Error opening connection stackTrace: org.sqlite.SQLiteConnection.open(SQLiteConnection.java:239)->org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61)->org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)->org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21)->org.sqlite.JDBC.createConnection(JDBC.java:115)->org.sqlite.JDBC.connect(JDBC.java:90)->java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)->java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)->core.Db.<clinit>(Db.java:30)->core.ApplicationContext.initFont(ApplicationContext.java:75)->core.ApplicationContext.init(ApplicationContext.java:65)->core.ui.MainActivity.<init>(MainActivity.java:65)->core.ui.MainActivity.main(MainActivity.java:303)
[!] Time:2021-02-22 12:33:45 ThreadId:1 Message:Cannot invoke "java.sql.PreparedStatement.setString(int, String)" because "preparedStatement" is null stackTrace: core.Db.getSetingValue(Db.java:337)->core.ApplicationContext.initFont(ApplicationContext.java:75)->core.ApplicationContext.init(ApplicationContext.java:65)->core.ui.MainActivity.<init>(MainActivity.java:65)->core.ui.MainActivity.main(MainActivity.java:303)
[!] Time:2021-02-22 12:33:45 ThreadId:1 Message:Cannot invoke "java.sql.PreparedStatement.setString(int, String)" because "preparedStatement" is null stackTrace: core.Db.getSetingValue(Db.java:337)->core.ApplicationContext.initFont(ApplicationContext.java:76)->core.ApplicationContext.init(ApplicationContext.java:65)->core.ui.MainActivity.<init>(MainActivity.java:65)->core.ui.MainActivity.main(MainActivity.java:303)
[!] Time:2021-02-22 12:33:45 ThreadId:1 Message:Cannot invoke "java.sql.PreparedStatement.setString(int, String)" because "preparedStatement" is null stackTrace: core.Db.getSetingValue(Db.java:337)->core.ApplicationContext.initFont(ApplicationContext.java:77)->core.ApplicationContext.init(ApplicationContext.java:65)->core.ui.MainActivity.<init>(MainActivity.java:65)->core.ui.MainActivity.main(MainActivity.java:303)
[!] Time:2021-02-22 12:33:45 ThreadId:1 Message:Cannot invoke "java.sql.PreparedStatement.setString(int, String)" because "preparedStatement" is null stackTrace: core.Db.getSetingValue(Db.java:337)->core.ApplicationContext.getGloballHttpHeader(ApplicationContext.java:366)->core.ApplicationContext.initHttpHeader(ApplicationContext.java:84)->core.ApplicationContext.init(ApplicationContext.java:66)->core.ui.MainActivity.<init>(MainActivity.java:65)->core.ui.MainActivity.main(MainActivity.java:303)
[!] Time:2021-02-22 12:33:45 ThreadId:1 Message:Cannot invoke "java.sql.Statement.executeQuery(String)" because "statement" is null stackTrace: core.Db.getAllPlugin(Db.java:246)->core.ApplicationContext.scanPluginJar(ApplicationContext.java:132)->core.ApplicationContext.init(ApplicationContext.java:67)->core.ui.MainActivity.<init>(MainActivity.java:65)->core.ui.MainActivity.main(MainActivity.java:303)
[*] Time:2021-02-22 12:33:45 ThreadId:1 Message: load pluginJar success! pluginJarNum:0 LoadPluginJarSuccessNum:0
[*] Time:2021-02-22 12:33:45 ThreadId:1 Message: load payload success! payloadMaxNum:3 onceLoadPayloadNum:3
[*] Time:2021-02-22 12:33:45 ThreadId:1 Message: load cryption success! cryptionMaxNum:6 onceLoadCryptionNum:6
[*] Time:2021-02-22 12:33:45 ThreadId:1 Message: load plugin success! pluginMaxNum:21 onceLoadPluginNum:21
[!] Time:2021-02-22 12:33:46 ThreadId:1 Message: 效验Hash成功   Hash Url:https://gitee.com/beichendram/Godzilla/raw/master/hashsumJar
效验Jar哈希:6053116ca6ae76d6abd0b6b2a4f13a20674f71824315e14b48bd3df28ef280d602ba3758daadd5c6252df35f291baa226aac5e0cebfb4d371e850876228832ad
本地Jar哈希:6053116ca6ae76d6abd0b6b2a4f13a20674f71824315e14b48bd3df28ef280d602ba3758daadd5c6252df35f291baa226aac5e0cebfb4d371e850876228832ad 
[!] Time:2021-02-22 12:33:46 ThreadId:1 Message:Cannot invoke "java.sql.PreparedStatement.setString(int, String)" because "preparedStatement" is null stackTrace: core.Db.getSetingValue(Db.java:337)->core.ui.MainActivity.<init>(MainActivity.java:68)->core.ui.MainActivity.main(MainActivity.java:303)
[!] Time:2021-02-22 12:33:46 ThreadId:1 Message:Cannot invoke "java.sql.Statement.executeQuery(String)" because "statement" is null stackTrace: core.Db.getAllShell(Db.java:78)->core.ui.MainActivity.initVariable(MainActivity.java:86)->core.ui.MainActivity.<init>(MainActivity.java:77)->core.ui.MainActivity.main(MainActivity.java:303)
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.Vector.get(int)" because "rows" is null
	at core.ui.MainActivity.initVariable(MainActivity.java:87)
	at core.ui.MainActivity.<init>(MainActivity.java:77)
	at core.ui.MainActivity.main(MainActivity.java:303)
                                                        
```

**Comment by BeichenDream** [comment]
加我微信:beichenxp

我看一下 应该和sqlite有关系

**Comment by BeichenDream** [comment]
sqlite版本问题
