### ISSUE TITLE
UI不全，可能是什么原因

### ISSUE THREAD

**Issue by lewoking** [BeichenDream/Godzilla#34]
[*] Time:2021-05-07 16:47:14 ThreadId:1 Message: load pluginJar success! pluginJarNum:0 LoadPluginJarSuccessNum:0
[*] Time:2021-05-07 16:47:14 ThreadId:1 Message: load payload success! payloadMaxNum:3 onceLoadPayloadNum:3
[*] Time:2021-05-07 16:47:14 ThreadId:1 Message: load cryption success! cryptionMaxNum:8 onceLoadCryptionNum:8
[*] Time:2021-05-07 16:47:15 ThreadId:1 Message: load plugin success! pluginMaxNum:22 onceLoadPluginNum:22
[!] Time:2021-05-07 16:47:19 ThreadId:1 Message: 效验Hash成功   Hash Url:https://gitee.com/beichendram/Godzilla/raw/master/hashsumJar
效验Jar哈希:e50ef51aa1714b9ccfe6d733714317e1d7adb37de264eae990d69394fb71367d28601c99cd1358fa5ab44a26a171f21203b932ad6ef11b104dbeac99bd1be96b
本地Jar哈希:e50ef51aa1714b9ccfe6d733714317e1d7adb37de264eae990d69394fb71367d28601c99cd1358fa5ab44a26a171f21203b932ad6ef11b104dbeac99bd1be96b
java.lang.reflect.InaccessibleObjectException: Unable to make field protected java.util.Vector javax.swing.table.DefaultTableModel.columnIdentifiers accessible: module java.desktop does not "opens javax.swing.table" to unnamed module @654b5005
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
	at core.ui.component.DataView.getColumnVector(DataView.java:148)
	at core.ui.component.DataView.AddRows(DataView.java:226)
	at core.ui.MainActivity.initVariable(MainActivity.java:97)
	at core.ui.MainActivity.<init>(MainActivity.java:85)
	at core.ui.MainActivity.main(MainActivity.java:383)

主界面如下图：
<img width="1124" alt="截屏2021-05-07 下午5 06 15" src="https://user-images.githubusercontent.com/8011483/117426543-96623980-af56-11eb-9742-0584aae1e66c.png">

**Comment by lewoking** [comment]
V3.02  显示正常
