### ISSUE TITLE
Godzilla4.0 有个空指针的bug,JDK11影响建立连接

### ISSUE THREAD

**Issue by wszme** [BeichenDream/Godzilla#64]
ThreadId:28 Message: java.lang.NullPointerException
        at util.functions.gzipD(functions.java:992)
        at shells.payloads.java.JavaShell_Cache.evalFunc(JavaShell.java:151)
        at shells.payloads.java.JavaShell_Cache.test(JavaShell.java:265)
        at core.shell.ShellEntity.initShellOpertion(ShellEntity.java:98)
        at core.ui.component.frame.ShellSetting.testButtonClick(ShellSetting.java:356)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at util.automaticBindClick$2.actionPerformed(automaticBindClick.java:82)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)

**Comment by BeichenDream** [comment]
替换shell生成的内容，将session替换成application

**Comment by wszme** [comment]
ok，多谢。
